#!/usr/bin/env ruby
require 'json'

list = JSON.parse(File.read('./all.json'))


list.each do |item|
  puts "// #{item['name']}"
  puts ".flag-#{item['alpha-3'].downcase} {"
  puts "  @include ratio(2/3);";
  puts "};"
end
#
#
