#!/usr/bin/env ruby

require 'json'
require 'awesome_print'

# Will create symlinks with real country name pointing to 3-letter iso code
# file. This makes searching with Ctrl-P much easier
class CreateSymlink
  def run
    `mkdir -p ../symlinks`
    all = JSON.parse(File.open('../flags.json', 'r').read)

    all.each do |country|
      country_name = country["name"].downcase.gsub(' ', '_').gsub('(', '').gsub(')','').gsub("'", '')
      alpha3 = country["alpha-3"].downcase
      scss_file = File.expand_path("../app/styles/_flags/#{alpha3}.scss")
      target_file = "../symlinks/#{country_name}.scss"
      `ln -sf #{scss_file} #{target_file}`
    end
  end
end
CreateSymlink.new.run

