#!/usr/bin/env bash

bower install
cd ./app/css/vendors

echo "Installing bourbon"
if ! which bourbon &>/dev/null; then
  gem install bourbon
fi
bourbon install

echo "Installing neat"
if ! which neat &>/dev/null; then
  gem install neat
fi
neat install

echo "Installing bitters"
if ! which bitters &>/dev/null; then
  gem install bitters
fi
bitters install
